### PR TITLE
DADT PSM update

### PR DESCRIPTION
**Pull request by brews**
This pull adds the Bayesian Mg/Ca PSM, and updates the Bayesian d18O, UK37, and TEX86 PSMs. Several minor general changes are also included. These changes include bug fixes, new species-specific PSMs, config options, and features for seasonality and "Deep Time" applications.

First, be sure to grab the latest versions of the PSM packages with:
```bash
conda install baysparpy baysplinepy deltaoxfox bayfox -c sbmalev
```

## TEX86
The TEX86 configs have been refactored to work with
`bayspar.predict_tex86()` options and the YAML config files.
The config class for the TEX86 PSM documents
the available options. Here, the big deal is the `temptype`
config option. This allows users to choose between the sea-surface
(`sst`) or gamma-average sub-surface (`subt`) calibrations. Whether you
change these or not depends on what your input state vector field is.

## UK37
UK37 PSM config options are described in the config class docstring.
These can be modified in the config YAML file. There aren't really
exciting new options available for the PSM, though.

Removed the unused MATLAB code for UK37. It's unused cruft.

## δ18O
Options for the δ18O PSMs can be set in `bayesreg_d18o` class, which are
described in the class docstrings. These can also be set in a YAML
config file. Key points:

* You can set `psm_d18osw_variable` to a salinity or seawater
δ18O field in the state vector. If it's salinity,
`psm_d18osw_from_salinity` must be `True` so that the PSM can predict
seawater δ18O from salinity. If we plug d18Osw in directly from the
state vector than use `False` -- this will be much faster to run.

* There is also a `seasonal_seatemp` config option. Setting this to
`True` tells the PSM to use the calibration based on seasonal SSTs and
not annual-means. `False` is just an annual-mean calibration which could
be useful for Deep Time DAs.

A δ18O PSM was added for *N. incompta* (`BayesRegD18oIncomptaPSM` or
`bayesreg_d18o_incompta`). So we can use species-specific calibration
for these samples now. Cool stuff.

A δ18O PSM was added for the "pooled" calibration. This is
`bayesreg_d18o_pooled` or `BayesRegD18oPooledPSM`. This is a catch-all
calibration (made by pooling all planktic species together). This might be useful for non-exant species -- say, for a DeepTime reanalysis.

This commit also changes the way the pre-calculated Ye files are named,
reflecting the wide range of options available for these PSMs.

There we several bug fixes to how seasonality was handled in d18O PSMs.

## Mg/Ca
This adds a new set of Bayesian PSMs for marine sediment Mg/Ca samples.
These PSMs are based on the `baymagpy` package. You can install this
package with `conda install baymagpy -c sbmalev`.

The new PSMs are include pooled (non-species specific) and hierarchical
(species specific) calibrations. The PSMs also have two variants "BCP"
or "Red". These represent the different lab cleaning procedures for
samples and need to be accounted for on a core-by-core basis. It also
makes the PSM classes a bit of a mess. Sorry about that.

The PSMs include several config options which are documented and shared
in the `bayesreg_mgca` config class. Configs can also be set in the
usual YAML config file. Configs to note:

* `seawater_age` - Optional correction for very old seawater
(Deep Time applications).
* `psm_omega_variable` - This is optional, fill it in with state
vector information if you have calcite saturation state (omega) fields.
Might be useful for Deep Time reanalysis.
* `seasonal_seatemp` - Whether to use the seasonal-SST or
annual-mean SST calibration.

## General changes
In build_ye.py, there is now an `if` at the bottom to catch when code is
run from terminal. This should prevent errors from the script grabbing
unintended system arguments if some poor soul tries to import it. This
also has a very basic config setup for the logging module. It now
prints logging messages to terminal that were previously ignored.

There were a few cases where an "error" message (might be) printed and
then SystemExit. I changed these to throw a KeyError(message) so that we
can get a full stack trace. There was a case where the code simply quits
without a message and it can easily be mistaken for successful
completion of the script.

In LMR_proxy.py, the logged ERROR message was change to a print to be
more consistent with how errors are handled elsewhere in that module.

### CODE REVIEW

**Comment by modons** [comment]
in the d18O comments, "This commit also changes the way the pre-calculated Ye files are named,
reflecting the wide range of options available for these PSMs." Is this local to DADT or affect global? I don't want to break everybody's prebuilt Ye files.

**Comment by brews** [comment]
@modons This should only influence how our Bayesian-y PSM files are named. With all the DTDA PSM changes, you all will likely want to rerun the prebuilt Ye script anyways.

**Comment by modons** [comment]
OK, thanks. I just don't want to break it for others, even if it is just a change to expected filenames.

**Comment by brews** [comment]
@modons Yeah, understood. I didn't touch that bit of the code.

Let me know when you're ready and I'll make this a proper pull request for you to accept. I wanted to make sure I have all the features and changes you guys need/want.

**Comment by modons** [comment]
Cool. I'm running a quickie recon just to see if anything breaks, and then will merge it onto production_develop. I'm a novice at handling pull requests, and just view them as a discussion before a commit. If there's any reason to handle this one with a "formal" request, please let me know.

**Comment by brews** [comment]
Nope. I think we're good. Slack me if anything breaks. I'm happy to help sort things out.

**Pull request merged**
